"""
Ushna Kaappaan — Telegram Early Warning Notification Service
Integrates with Telegram Bot API with automatic, transparent fallback to MOCK/TEST transport.
"""

import requests
from datetime import datetime, timezone
from typing import Dict, Any, Optional
import logging

from backend.config import settings
from backend.models import TelegramDelivery, AuditLog

logger = logging.getLogger("ushna.telegram")

class TelegramService:
    def __init__(self):
        self.bot_token = settings.TELEGRAM_BOT_TOKEN
        self.default_chat_id = settings.TELEGRAM_CHAT_ID
        self.api_url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage" if self.bot_token else None

    @property
    def is_configured(self) -> bool:
        return bool(self.bot_token and len(self.bot_token) > 10)

    def format_alert_message(
        self,
        district_name: str,
        state: str,
        utci_c: float,
        utci_category: str,
        operational_severity: str,
        advisory_text: str,
        timestamp_ist: str,
        recipient_role: str,
        mode: str = "LIVE"
    ) -> str:
        """
        Formats structured early-warning telegram message with official headers and clean layout.
        """
        mode_tag = "🔴 [LIVE SYSTEM ALERT]" if mode == "LIVE" else "🟡 [DEMO / TEST SCENARIO]"
        
        msg = (
            f"🔥 *USHNA KAAPPAAN — HEAT EARLY WARNING*\n"
            f"{mode_tag}\n\n"
            f"📍 *District:* {district_name}, {state}\n"
            f"🌡 *Thermal Stress (UTCI):* `{utci_c:.1f}°C`\n"
            f"⚠️ *Category:* {utci_category}\n"
            f"🚨 *Operational Severity:* {operational_severity}\n"
            f"👥 *Target Role:* {recipient_role}\n"
            f"🕒 *Time:* {timestamp_ist}\n\n"
            f"📋 *Suggested Precautionary Actions:*\n{advisory_text}\n\n"
            f"⚠️ _Note: Advisory generated for decision support. Official directives are issued by competent administrative authorities._\n"
            f"ℹ️ _Generated by Ushna Kaappaan Localized Heat Early Warning Platform._"
        )
        return msg

    def send_notification(
        self,
        db_session,
        alert_id: Optional[int],
        district_name: str,
        state: str,
        utci_c: float,
        utci_category: str,
        operational_severity: str,
        advisory_text: str,
        timestamp_ist: str,
        recipient_role: str,
        chat_id: Optional[str] = None,
        mode: str = "LIVE"
    ) -> Dict[str, Any]:
        target_chat_id = chat_id or self.default_chat_id or "MOCK_CHANNEL_SOUTH_INDIA"
        message_body = self.format_alert_message(
            district_name, state, utci_c, utci_category, operational_severity,
            advisory_text, timestamp_ist, recipient_role, mode
        )

        transport_mode = "REAL" if (self.is_configured and target_chat_id != "MOCK_CHANNEL_SOUTH_INDIA") else "MOCK"
        delivery_status = "SENT" if transport_mode == "REAL" else "MOCK / TEST - NOT ACTUALLY SENT"
        error_msg = None

        if transport_mode == "REAL":
            try:
                payload = {
                    "chat_id": target_chat_id,
                    "text": message_body,
                    "parse_mode": "Markdown"
                }
                resp = requests.post(self.api_url, json=payload, timeout=10)
                if resp.status_code != 200:
                    delivery_status = "FAILED"
                    error_msg = f"HTTP {resp.status_code}: {resp.text}"
                    logger.error(f"Telegram real delivery failed: {error_msg}")
                else:
                    delivery_status = "SENT"
                    logger.info(f"Telegram real alert sent to {target_chat_id} for {district_name}")
            except Exception as e:
                delivery_status = "FAILED"
                error_msg = str(e)
                logger.error(f"Telegram connection error: {e}")
        else:
            # Mock / Test transport — no real network send
            delivery_status = "MOCK / TEST - NOT ACTUALLY SENT"
            logger.info(f"[MOCK / TEST] Early warning prepared for {target_chat_id} ({recipient_role}) in {district_name}")

        # Persist delivery record in DB
        delivery_record = TelegramDelivery(
            alert_id=alert_id,
            recipient_role=recipient_role,
            chat_id=target_chat_id,
            message_body=message_body,
            transport_mode=transport_mode,
            delivery_status=delivery_status,
            error_message=error_msg,
            sent_at=datetime.now(timezone.utc)
        )
        if db_session:
            db_session.add(delivery_record)
            db_session.commit()
            db_session.refresh(delivery_record)

        return {
            "delivery_id": delivery_record.id if db_session else None,
            "transport_mode": transport_mode,
            "delivery_status": delivery_status,
            "chat_id": target_chat_id,
            "recipient_role": recipient_role,
            "message_body": message_body,
            "error_message": error_msg,
            "is_real_telegram": (transport_mode == "REAL" and delivery_status == "SENT")
        }

telegram_service = TelegramService()
